"""Add AdminUser table

Revision ID: 1a45a947cf87
Revises: s7t8u9v0w1x2
Create Date: 2026-09-16 18:40:50.010039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '1a45a947cf87'
down_revision: Union[str, None] = 's7t8u9v0w1x2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_user_email', 'adminuser', ['email'], unique=False)
    op.create_index(op.f('ix_adminuser_user_uuid'), 'adminuser', ['user_uuid'], unique=False)
    op.drop_index(op.f('ix_demo_entity_kind'), table_name='demo_entity')
    op.drop_index(op.f('ix_demo_entity_org_id'), table_name='demo_entity')
    op.drop_index(op.f('ix_demo_entity_uuid'), table_name='demo_entity')
    op.drop_table('demo_entity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_entity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bundle_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('demo_entity_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('demo_entity_pkey')),
    sa.UniqueConstraint('kind', 'bundle_key', name=op.f('uq_demo_entity_kind_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_demo_entity_uuid'), 'demo_entity', ['entity_uuid'], unique=False)
    op.create_index(op.f('ix_demo_entity_org_id'), 'demo_entity', ['org_id'], unique=False)
    op.create_index(op.f('ix_demo_entity_kind'), 'demo_entity', ['kind'], unique=False)
    op.drop_index(op.f('ix_adminuser_user_uuid'), table_name='adminuser')
    op.drop_index('ix_admin_user_email', table_name='adminuser')
    op.drop_table('adminuser')
    # ### end Alembic commands ###
