"""Add missing fields to AdminUser

Revision ID: 3a7093b9019f
Revises: 1a45a947cf87
Create Date: 2026-09-16 18:52:53.169966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '3a7093b9019f'
down_revision: Union[str, None] = '1a45a947cf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminuser', sa.Column('email_verified', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('adminuser', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('adminuser', sa.Column('locked_until', sa.String(), nullable=True))
    op.add_column('adminuser', sa.Column('last_login_at', sa.String(), nullable=True))
    op.add_column('adminuser', sa.Column('last_login_ip', sa.String(), nullable=True))
    op.add_column('adminuser', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adminuser', 'password_changed_at')
    op.drop_column('adminuser', 'last_login_ip')
    op.drop_column('adminuser', 'last_login_at')
    op.drop_column('adminuser', 'locked_until')
    op.drop_column('adminuser', 'failed_login_attempts')
    op.drop_column('adminuser', 'email_verified')
    # ### end Alembic commands ###
